export const SITE_URL = "https://cellivo.com";
export const DEFAULT_OG_IMAGE = `${SITE_URL}/og-home.jpg`;

export const legacyRedirects = {
  "/about-us": "/about",
  "/contact-us": "/contact",
  "/affiliate-program": "/affiliate",
  "/signup": "/pricing",
  "/privacy-policy": "/privacy",
  "/start-free-trail": "/pricing",
  "/hello-world": "/blog",
  "/category/uncategorized": "/blog",
  "/features/advanced-security-and-user-access-control": "/settings-security-integrations",
  "/features/fully-customizable-system-settings": "/settings-security-integrations",
  "/features/supplier-and-purchase-management": "/customers-suppliers-management",
  "/features/customer-relationship-management": "/customers-suppliers-management",
  "/features/detailed-sales-reports-and-analytics": "/features",
  "/features/complete-mobile-repair-management-system": "/mobile-repair-management-software",
  "/features/inventory-management-with-imei-serial-no": "/imei-tracking-pos-system",
  "/features/smart-pos-billing-for-mobile-shops": "/billing-software-for-mobile-shop",
  "/features/interactive-dashboard-with-real-time-widgets": "/features",
  "/knowledge-base": "/blog",
  "/knowledge-base/system-settings": "/settings-security-integrations",
  "/knowledge-base/supplier-records": "/customers-suppliers-management",
  "/knowledge-base/revenue-reporting-system": "/features",
  "/knowledge-base/quick-dashboard": "/features",
  "/knowledge-base/inventory-management": "/inventory-management-system",
  "/knowledge-base/how-to-get-payment": "/billing-software-for-mobile-shop",
  "/knowledge-base/device-repairs": "/mobile-repair-management-software",
  "/knowledge-base/customer-records": "/customers-suppliers-management",
  "/knowledge-base/about-help-center": "/blog",
  "/pos-billing-system": "/billing-software-for-mobile-shop",
  "/inventory-imei-tracking": "/imei-tracking-pos-system",
  "/imei-tracking": "/imei-tracking-pos-system",
  "/imei-tracking-pos": "/imei-tracking-pos-system",
  "/repair-management-system": "/mobile-repair-management-software",
  "/repair-management": "/mobile-repair-management-software",
  "/multi-branch-pos": "/multi-branch-pos-system",
};

export const sitemapEntries = [
  { path: "/", changefreq: "weekly", priority: "1.0" },
  { path: "/about", changefreq: "monthly", priority: "0.7" },
  { path: "/contact", changefreq: "monthly", priority: "0.8" },
  { path: "/pricing", changefreq: "weekly", priority: "0.8" },
  { path: "/affiliate", changefreq: "monthly", priority: "0.7" },
  { path: "/features", changefreq: "weekly", priority: "0.9" },
  { path: "/blog", changefreq: "weekly", priority: "0.8" },
  { path: "/mobile-shop-pos-system", changefreq: "weekly", priority: "0.95" },
  { path: "/pos-system-for-phone-shop", changefreq: "weekly", priority: "0.92" },
  { path: "/pos-for-mobile-shops", changefreq: "monthly", priority: "0.78" },
  { path: "/pos-system-sri-lanka", changefreq: "monthly", priority: "0.78" },
  { path: "/billing-software-for-mobile-shop", changefreq: "weekly", priority: "0.88" },
  { path: "/imei-tracking-pos-system", changefreq: "weekly", priority: "0.88" },
  { path: "/inventory-management-system", changefreq: "weekly", priority: "0.88" },
  { path: "/mobile-repair-management-software", changefreq: "weekly", priority: "0.88" },
  { path: "/multi-branch-pos-system", changefreq: "weekly", priority: "0.86" },
  { path: "/cash-drawer-management", changefreq: "monthly", priority: "0.8" },
  { path: "/customer-loyalty-system", changefreq: "monthly", priority: "0.8" },
  { path: "/banking-credit-cheques", changefreq: "monthly", priority: "0.78" },
  { path: "/staff-commissions-payroll", changefreq: "monthly", priority: "0.78" },
  { path: "/customers-suppliers-management", changefreq: "monthly", priority: "0.72" },
  { path: "/settings-security-integrations", changefreq: "monthly", priority: "0.74" },
  { path: "/integrations", changefreq: "monthly", priority: "0.76" },
  { path: "/privacy", changefreq: "yearly", priority: "0.3" },
  { path: "/terms", changefreq: "yearly", priority: "0.3" },
  { path: "/refund-policy", changefreq: "yearly", priority: "0.3" },
];
