import type { ComponentType } from "react";
import type { RouteObject } from "react-router-dom";
import { Navigate } from "react-router-dom";
import AdminProtectedRoute from "@/components/admin/AdminProtectedRoute";

export const pageFiles = {
  Index: "./pages/Index.tsx",
  Login: "./pages/Login.tsx",
  Signup: "./pages/Signup.tsx",
  AdminLogin: "./pages/AdminLogin.tsx",
  AdminDashboard: "./pages/AdminDashboard.tsx",
  AdminPosts: "./pages/AdminPosts.tsx",
  AdminCustomerLogos: "./pages/AdminCustomerLogos.tsx",
  AdminTestimonials: "./pages/AdminTestimonials.tsx",
  AdminPricingLinks: "./pages/AdminPricingLinks.tsx",
  AdminSettings: "./pages/AdminSettings.tsx",
  About: "./pages/About.tsx",
  Affiliate: "./pages/Affiliate.tsx",
  Features: "./pages/Features.tsx",
  Contact: "./pages/Contact.tsx",
  Pricing: "./pages/Pricing.tsx",
  Blog: "./pages/Blog.tsx",
  BlogPost: "./pages/BlogPost.tsx",
  BlogAdmin: "./pages/BlogAdmin.tsx",
  BlogAdminPreview: "./pages/BlogAdminPreview.tsx",
  PrivacyPolicy: "./pages/PrivacyPolicy.tsx",
  TermsOfService: "./pages/TermsOfService.tsx",
  RefundPolicy: "./pages/RefundPolicy.tsx",
  NotFound: "./pages/NotFound.tsx",
  MobileShopPosSystem: "./pages/MobileShopPosSystem.tsx",
  PosBillingSystem: "./pages/PosBillingSystem.tsx",
  ImeiTrackingPos: "./pages/ImeiTrackingPos.tsx",
  InventoryManagement: "./pages/InventoryManagement.tsx",
  RepairManagement: "./pages/RepairManagement.tsx",
  MultiBranchPos: "./pages/MultiBranchPos.tsx",
  CashDrawerManagement: "./pages/CashDrawerManagement.tsx",
  CustomerLoyaltySystem: "./pages/CustomerLoyaltySystem.tsx",
  BankingCredit: "./pages/BankingCredit.tsx",
  StaffCommissions: "./pages/StaffCommissions.tsx",
  CustomersSuppliers: "./pages/CustomersSuppliers.tsx",
  SettingsSecurity: "./pages/SettingsSecurity.tsx",
  PosForMobileShops: "./pages/PosForMobileShops.tsx",
  PosSystemForPhoneShop: "./pages/PosSystemForPhoneShop.tsx",
  PosSystemSriLanka: "./pages/PosSystemSriLanka.tsx",
  Integrations: "./pages/Integrations.tsx",
} as const;

export type PagePath = keyof typeof pageFiles;
export type PageModule = { default: ComponentType };
export type PageComponents = Record<PagePath, ComponentType>;

export const normalizePathname = (pathname: string) => {
  if (!pathname || pathname === "/") return "/";

  const lowerCased = pathname.toLowerCase();
  return lowerCased.endsWith("/") ? lowerCased.slice(0, -1) || "/" : lowerCased;
};

export const routePreloadLookup: Record<string, PagePath> = {
  "/": "Index",
  "/login": "Login",
  "/signup": "Pricing",
  "/admin/login": "AdminLogin",
  "/admin": "AdminDashboard",
  "/admin/posts": "AdminPosts",
  "/admin/customer-logos": "AdminCustomerLogos",
  "/admin/testimonials": "AdminTestimonials",
  "/admin/pricing-links": "AdminPricingLinks",
  "/admin/settings": "AdminSettings",
  "/admin/seo-settings": "AdminSettings",
  "/about": "About",
  "/affiliate": "Affiliate",
  "/features": "Features",
  "/pricing": "Pricing",
  "/contact": "Contact",
  "/blog": "Blog",
  "/admin/blog": "BlogAdmin",
  "/privacy": "PrivacyPolicy",
  "/terms": "TermsOfService",
  "/refund-policy": "RefundPolicy",
  "/mobile-shop-pos-system": "MobileShopPosSystem",
  "/billing-software-for-mobile-shop": "PosBillingSystem",
  "/imei-tracking-pos-system": "ImeiTrackingPos",
  "/inventory-management-system": "InventoryManagement",
  "/mobile-repair-management-software": "RepairManagement",
  "/multi-branch-pos-system": "MultiBranchPos",
  "/cash-drawer-management": "CashDrawerManagement",
  "/customer-loyalty-system": "CustomerLoyaltySystem",
  "/banking-credit-cheques": "BankingCredit",
  "/staff-commissions-payroll": "StaffCommissions",
  "/customers-suppliers-management": "CustomersSuppliers",
  "/settings-security-integrations": "SettingsSecurity",
  "/integrations": "Integrations",
  "/pos-for-mobile-shops": "PosForMobileShops",
  "/pos-system-for-phone-shop": "PosSystemForPhoneShop",
  "/pos-system-sri-lanka": "PosSystemSriLanka",
};

export const buildAppRoutes = ({
  About,
  Affiliate,
  AdminCustomerLogos,
  AdminDashboard,
  AdminLogin,
  AdminPosts,
  AdminPricingLinks,
  AdminSettings,
  AdminTestimonials,
  BankingCredit,
  Blog,
  BlogAdmin,
  BlogAdminPreview,
  BlogPost,
  CashDrawerManagement,
  Contact,
  CustomerLoyaltySystem,
  CustomersSuppliers,
  Features,
  ImeiTrackingPos,
  Index,
  Integrations,
  InventoryManagement,
  Login,
  MobileShopPosSystem,
  MultiBranchPos,
  NotFound,
  PosBillingSystem,
  PosForMobileShops,
  PosSystemForPhoneShop,
  PosSystemSriLanka,
  Pricing,
  PrivacyPolicy,
  RefundPolicy,
  RepairManagement,
  SettingsSecurity,
  Signup,
  StaffCommissions,
  TermsOfService,
}: PageComponents): RouteObject[] => [
  { path: "/", element: <Index /> },
  { path: "/login", element: <Login /> },
  { path: "/signup", element: <Navigate to="/pricing" replace /> },
  { path: "/admin/login", element: <AdminLogin /> },
  { path: "/admin", element: <AdminProtectedRoute><AdminDashboard /></AdminProtectedRoute> },
  { path: "/admin/posts", element: <AdminProtectedRoute><AdminPosts /></AdminProtectedRoute> },
  { path: "/admin/customer-logos", element: <AdminProtectedRoute><AdminCustomerLogos /></AdminProtectedRoute> },
  { path: "/admin/testimonials", element: <AdminProtectedRoute><AdminTestimonials /></AdminProtectedRoute> },
  { path: "/admin/pricing-links", element: <AdminProtectedRoute><AdminPricingLinks /></AdminProtectedRoute> },
  { path: "/admin/settings", element: <AdminProtectedRoute><AdminSettings /></AdminProtectedRoute> },
  { path: "/admin/seo-settings", element: <Navigate to="/admin/settings" replace /> },
  { path: "/about", element: <About /> },
  { path: "/affiliate-program", element: <Navigate to="/affiliate" replace /> },
  { path: "/affiliate", element: <Affiliate /> },
  { path: "/features", element: <Features /> },
  { path: "/pricing", element: <Pricing /> },
  { path: "/contact", element: <Contact /> },
  { path: "/blog", element: <Blog /> },
  { path: "/blog/:slug", element: <BlogPost /> },
  { path: "/admin/blog", element: <AdminProtectedRoute><BlogAdmin /></AdminProtectedRoute> },
  { path: "/admin/blog/preview/:id", element: <AdminProtectedRoute><BlogAdminPreview /></AdminProtectedRoute> },
  { path: "/pos-billing-system", element: <Navigate to="/billing-software-for-mobile-shop" replace /> },
  { path: "/billing-software-for-mobile-shop", element: <PosBillingSystem /> },
  { path: "/inventory-imei-tracking", element: <Navigate to="/imei-tracking-pos-system" replace /> },
  { path: "/imei-tracking", element: <Navigate to="/imei-tracking-pos-system" replace /> },
  { path: "/imei-tracking-pos", element: <Navigate to="/imei-tracking-pos-system" replace /> },
  { path: "/imei-tracking-pos-system", element: <ImeiTrackingPos /> },
  { path: "/inventory-management-system", element: <InventoryManagement /> },
  { path: "/repair-management-system", element: <Navigate to="/mobile-repair-management-software" replace /> },
  { path: "/repair-management", element: <Navigate to="/mobile-repair-management-software" replace /> },
  { path: "/mobile-repair-management-software", element: <RepairManagement /> },
  { path: "/multi-branch-pos", element: <Navigate to="/multi-branch-pos-system" replace /> },
  { path: "/multi-branch-pos-system", element: <MultiBranchPos /> },
  { path: "/cash-drawer-management", element: <CashDrawerManagement /> },
  { path: "/customer-loyalty-system", element: <CustomerLoyaltySystem /> },
  { path: "/banking-credit-cheques", element: <BankingCredit /> },
  { path: "/staff-commissions-payroll", element: <StaffCommissions /> },
  { path: "/customers-suppliers-management", element: <CustomersSuppliers /> },
  { path: "/settings-security-integrations", element: <SettingsSecurity /> },
  { path: "/integrations", element: <Integrations /> },
  { path: "/mobile-shop-pos-system", element: <MobileShopPosSystem /> },
  { path: "/pos-for-mobile-shops", element: <PosForMobileShops /> },
  { path: "/pos-system-for-phone-shop", element: <PosSystemForPhoneShop /> },
  { path: "/pos-system-sri-lanka", element: <PosSystemSriLanka /> },
  { path: "/privacy", element: <PrivacyPolicy /> },
  { path: "/terms", element: <TermsOfService /> },
  { path: "/refund-policy", element: <RefundPolicy /> },
  { path: "*", element: <NotFound /> },
];
